#!/usr/bin/env bash
# Display information about a site's subdomains

SUBDOMAINS=("www" "lb-01" "web-01" "web-02")

print_details ()
{
    dig "$2.$1" | awk -v subd="$2" '/ANSWER SECTION:/ \
	{ getline; print "The subdomain " subd " is a " $4 " record and points to " $5}'
}

if [ -z "$2" ]; then
   for sub in "${SUBDOMAINS[@]}"
   do
	   print_details "$1" "$sub"
   done
else
    print_details "$1" "$2"
fi
