#!/usr/bin/env bash
# Install nginx, redirect /redirect_me location to a youtube video

REDIRECT="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n }\n"
FILE="/etc/nginx/sites-available/default"

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World' > /var/www/html/index.html

sudo sed -i.bak "/^server \{.*/a $REDIRECT" "$FILE"

sudo service nginx start
