#!/usr/bin/env bash
# Install nginx, redirect /redirect_me location to a youtube video

REDIRECT=' \
\tlocation /redirect_me/ { \
\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
\t}'
FILE="/etc/nginx/sites-available/default"

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo sed -i "/^server {.*/a $REDIRECT" "$FILE"

sudo service nginx start
