#!/usr/bin/env bash
# Install nginx, redirect /redirect_me location to a youtube video
# Add 404 error page

REDIRECT='rewrite ^/redirect_me http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
NOT_FOUND=' \
\terror_page 404 /custom_404.html;'
ALL="$REDIRECT\n$NOT_FOUND"

FILE="/etc/nginx/sites-available/default"

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i "/^server {.*/a $ALL" "$FILE"

sudo service nginx start
