#!/usr/bin/env bash
# Install haproxy and do some setup

CONFIG=' \
\
frontend http \
\tbind *:80 \
\tdefault_backend web-backend \
\
backend web-backend \
\tbalance roundrobin \
\tserver 235208-web-01 100.26.165.122:80 \
\tserver 235208-web-02 100.26.215.117:80'

FILE="/etc/haproxy/haproxy.cfg"

# Install haproxy
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*

sudo sed -i "\$a$CONFIG" "$FILE"

sudo sed -i "\$aENABLED=1" /etc/default/haproxy

sudo haproxy -db -f "$FILE"

sudo service haproxy start
