#!/usr/bin/env bash
# Prints "To infinity and beyond"
# traps SIGTERM, SIGINT, SIGQUIT

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?"' SIGINT

while (true)
do
	echo "To infinity and beyond"
	sleep 2
done
