#!/usr/bin/env bash
# Reads and displays formatted content of /etc/passwd

file="/etc/passwd"

while read -r line
do
	IFS=:
	read -r -a fields <<< "$line"
	if [ -z "${fields[4]}" ]; then
		fields[4]=${fields[0]}
	fi
	echo "The user ${fields[0]} is part of the ${fields[3]} gang," \
		"lives in ${fields[5]} and rides ${fields[6]}." \
		"${fields[2]}'s place is protected by the passcode ${fields[1]}," \
		"more info about the user here: ${fields[4]}"
done < "$file"
