#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while
# displaying different messages on the 4th and 8th iterations

MAX=10
count=1

while [ $count -le $MAX ]
do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
