#!/usr/bin/env bash
# This script is displaying numebers from 1 to 20,
# with extra messages on the 4th, 9th and 17th iterations

MAX=20
count=1

while [ $count -le $MAX ]
do
	echo "${count}"
	case "$count" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			true
	esac
	(( count++ ))
done
