#!/usr/bin/env bash
# This script gives information on a file named 'school'

if [ -f school ] || [ -d school ]; then
	echo "school file exists"

	size=$(find . -name "school" -printf "%s")

	if [ "$size" == "0" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f school ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
