#!/usr/bin/env bash
# Set Apache to return 'Hello Holberton' when querying the root

sudo apt-get update
sudo apt-get -y install apache2
sudo mkdir -p /var/www/html
echo 'Hello Holberton' | sudo tee /var/www/html/index.html
sudo service apache2 start
