#!/usr/bin/env bash
# Start nginx with the nginx user as root process
sudo sed -i 's/#user www-data/user nginx:nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx nginx
